owners:
  - owner:
      name: Dave
      teams:
        - NYG
        - NYJ
        - LAC
        - DEN
  - owner:
      name: Meat
      teams:
        - WAS
        - MIA
        - ARI
        - HOU
  - owner:
      name: Steve
      teams:
        - CIN
        - CAR
        - CHI
        - CLE
  - owner:
      name: George
      teams:
        - JAX
        - DET
        - LVR
        - ATL
