owners:
  - owner:
      name: Dave
      teams:
        - HOU
        - LAR
        - CHI
        - ATL
  - owner:
      name: Meat
      teams:
        - TAM
        - WAS
        - PIT
        - GNB
  - owner:
      name: Steve
      teams:
        - IND
        - LVR
        - NWE
        - DEN
  - owner:
      name: George
      teams:
        - ARI
        - CAR
        - NYG
        - TEN
