owners:
  - owner:
      name: Dave
      teams:
        - MIA
        - NYG
        - ATL
        - CIN
  - owner:
      name: AI Meat
      teams:
        - ARI
        - CAR
        - WAS
        - JAX
  - owner:
      name: Steve
      teams:
        - NYJ
        - TEN
        - MIN
        - PIT
  - owner:
      name: George
      teams:
        - CLE
        - LVR
        - NOR
        - IND